apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-node-app-depl
  labels: 
    app: node-app
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app 
    spec: 
      containers: 
        - name: node-app
          image: siradev22/kaiburrnode
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-lb-srv
spec: 
  selector:
    app: node-app
  type: LoadBalancer
  ports: 
    - protocol: TCP 
      port: 5200
      targetPort: 3000