apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-react-app-depl
  labels: 
    app: react-app
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app 
    spec: 
      containers: 
        - name: react-app
          image: siradev22/kaiburr
          ports:
          - containerPort: 3000
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: react-service
# spec: 
#   type: NodePort
#   selector:
#     app: react-app
#   ports: 
#     - name: http
#       protocol: TCP
#       port: 80
#       targetPort: 3000

# # apiVersion: v1
# # kind: Service
# # metadata:
# #   name: react-np-srv
# #   labels:
# #     name: np-srv
# # spec:
# #   type: NodePort
# #   ports:
# #     - port: 80
# #       nodePort: 30080
# #       name: http
# #     - port: 443
# #       nodePort: 30443
# #       name: https
# #   selector:
# #     name: react-app
# ---
apiVersion: v1
kind: Service
metadata:
  name: react-lb-srv
spec: 
  selector:
    app: react-app
  type: LoadBalancer
  ports: 
    - protocol: TCP 
      port: 5100
      targetPort: 3000

#       # kubectl expose deployment my-react-app-depl --type=NodePort --port=8080
#       #  kubectl exec my-react-app-depl-68b5867bf8-g4fcc bash 
#       # kubectl get nodes -o wide
