apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-spring-app-depl
  labels: 
    app: spring-app
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app 
    spec: 
      containers: 
        - name: spring-app
          image: siradev22/spring_be
          ports:
          - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: spring-lb-srv
spec: 
  selector:
    app: node-app
  type: LoadBalancer
  ports: 
    - protocol: TCP 
      port: 5300
      targetPort: 5001