apiVersion: v1
kind: Service
metadata: 
  name: mongodb
  labels: 
    app: mongodb
spec: 
  clusterIP: None
  selector:
    app: mongodb
  ports: 
    - port: 27017
      targetPort: 27017
      
  # kubectl scale statefulset mongodb --replicas=3

  # kubectl run -it mongo-shell --image=mongo:5.0.16 --rm -- /bin/bash
  # http://mongodb-0.mongodb.default.svc.cluster.local
